# Generated by Django 4.2.7 on 2024-11-27 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='FromMessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FromMessage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ToMessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToMessage', to=settings.AUTH_USER_MODEL),
        ),
    ]
