# Generated by Django 4.2.7 on 2024-12-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hastage',
            field=models.TextField(null=True),
        ),
    ]
