# Generated by Django 4.2.7 on 2024-12-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_post_hastage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privet_account',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
