# Generated by Django 4.2.7 on 2024-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_profile_privet_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='https://th.bing.com/th/id/OIP.DzBlyLi5oo0RCww-wose6wAAAA?rs=1&pid=ImgDetMain', upload_to='Profile_image'),
        ),
    ]
